# Generated by Django 4.0.5 on 2022-07-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='images')),
                ('image3', models.ImageField(upload_to='images')),
                ('date', models.DateField()),
            ],
        ),
    ]
