# Generated by Django 4.0.5 on 2022-07-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
