# Generated by Django 4.0.5 on 2022-07-29 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0004_alter_project_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image3',
        ),
    ]
