# Generated by Django 4.0.5 on 2022-07-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0005_remove_project_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image2',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
