# Generated by Django 4.0.5 on 2022-07-29 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0006_project_image2_alter_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='project',
            name='image3',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='project',
            name='image4',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
