# Generated by Django 4.0.5 on 2022-07-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0007_rename_image_project_image1_project_image3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
