# Generated by Django 4.0.5 on 2022-07-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0008_alter_project_image1_alter_project_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='project',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
