# Generated by Django 4.0.5 on 2022-08-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0009_project_image5_project_image6'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_description', models.TextField(max_length=1500)),
                ('my_image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_description', models.TextField(max_length=1000)),
                ('company_image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
