# Generated by Django 4.0.5 on 2022-08-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0010_aboutme_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image1', models.ImageField(blank=True, null=True, upload_to='images')),
                ('slider_image2', models.ImageField(blank=True, null=True, upload_to='images')),
                ('slider_image3', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='company_description',
            field=models.TextField(max_length=1500),
        ),
    ]
